name: testwork
run-name: testwork ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      param1:
        description: param1
        type: string
        default: "param1 value"
      param2:
        description: param2
        type: string
        default: "param2 value"
      param3:
        description: param3
        type: string
        default: "param3 value"
      param4:
        description: param4
        type: string
        default: "param4 value"
      param5:
        description: param5
        type: string
        default: "param5 value"
      param6:
        description: param6
        type: string
        default: "param6 value"
      param7:
        description: param7
        type: string
        default: "param7 value"
      param8:
        description: param8
        type: string
        default: "param8 value"
      param9:
        description: param9
        type: string
        default: "param9 value"
      param10:
        description: param10
        type: string
        default: "param10 value"
      param11:
        description: param11
        type: string
        default: "param11 value"
      param12:
        description: param12
        type: string
        default: "param12 value"
      param13:
        description: param13
        type: string
        default: "param13 value"
      param14:
        description: param14
        type: string
        default: "param14 value"
      param15:
        description: param15
        type: string
        default: "param15 value"
      param16:
        description: param16
        type: string
        default: "param16 value"
      param17:
        description: param17
        type: string
        default: "param17 value"
      param18:
        description: param18
        type: string
        default: "param18 value"
      param19:
        description: param19
        type: string
        default: "param19 value"
      param20:
        description: param20
        type: string
        default: "param20 value"
      param21:
        description: param21
        type: string
        default: "param21 value"
      param22:
        description: param22
        type: string
        default: "param22 value"
      param23:
        description: param23
        type: string
        default: "param23 value"
      param24:
        description: param24
        type: string
        default: "param24 value"
      param25:
        description: param25
        type: string
        default: "param25 value"
      param26:
        description: param26
        type: string
        default: "param26 value"
      param27:
        description: param27
        type: string
        default: "param27 value"
      param28:
        description: param28
        type: string
        default: "param28 value"
      param29:
        description: param29
        type: string
        default: "param29 value"
      param30:
        description: param30
        type: string
        default: "param30 value"

jobs:
  output_parameters:
    runs-on: ubuntu-slim
    steps:
      - name: Hello World
        run: echo "Hello world!"
      
      - name: Output Parameters
        run: |
          echo Parameter 1 is ${{ inputs.param1 }}
          echo Parameter 2 is ${{ inputs.param2 }}
          echo Parameter 3 is ${{ inputs.param3 }}
          echo Parameter 4 is ${{ inputs.param4 }}
          echo Parameter 5 is ${{ inputs.param5 }}
          echo Parameter 6 is ${{ inputs.param6 }}
          echo Parameter 7 is ${{ inputs.param7 }}
          echo Parameter 8 is ${{ inputs.param8 }}
          echo Parameter 9 is ${{ inputs.param9 }}
          echo Parameter 10 is ${{ inputs.param10 }}
          echo Parameter 11 is ${{ inputs.param11 }}
          echo Parameter 12 is ${{ inputs.param12 }}
          echo Parameter 13 is ${{ inputs.param13 }}
          echo Parameter 14 is ${{ inputs.param14 }}
          echo Parameter 15 is ${{ inputs.param15 }}
          echo Parameter 16 is ${{ inputs.param16 }}
          echo Parameter 17 is ${{ inputs.param17 }}
          echo Parameter 18 is ${{ inputs.param18 }}
          echo Parameter 19 is ${{ inputs.param19 }}
          echo Parameter 20 is ${{ inputs.param20 }}
          echo Parameter 21 is ${{ inputs.param21 }}
          echo Parameter 22 is ${{ inputs.param22 }}
          echo Parameter 23 is ${{ inputs.param23 }}
          echo Parameter 24 is ${{ inputs.param24 }}
          echo Parameter 25 is ${{ inputs.param25 }}
          echo Parameter 26 is ${{ inputs.param26 }}
          echo Parameter 27 is ${{ inputs.param27 }}
          echo Parameter 28 is ${{ inputs.param28 }}
          echo Parameter 29 is ${{ inputs.param29 }}
          echo Parameter 30 is ${{ inputs.param30 }}